name: erdos
dependencies:
    - python=3.8
    - pandas=1.0.*
    - numpy=1.18.*
    - ipykernel=5.1.*
    - jupyterlab=1.2.*
    - scikit-learn=0.22.1
    - nb_conda_kernels=2.2.*
    - flask
    - gunicorn
    - pip
